### ISSUE TITLE
不支持mp3格式？

### ISSUE THREAD

**Issue by zhujitop** [juzhiyuan/wordpress-cdn#11]
配置的是阿里云，图片是正常的。

但是上传mp3的时候错误了。
1：本地服务器没有；
2：阿里云oss那边也没有。

上传提示：
从服务器收到预料之外的响应。此文件可能已被成功上传。请检查媒体库或刷新本页。

但是两边都没有，不用插件的时候正常可用。

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/71703759-64484100-2e11-11ea-8c6f-2073e9ebc8c5.png)

我这边可以正确上传，方便的话可以添加我的微信 JuShaoyao，周六日可以帮你远程调试一下~~

**Comment by juzhiyuan** [comment]
请问 OSS 与 ECS 是否在同一个可用区内？如果跨区上传可能因为网络抖动造成上传失败，建议使用同一区域的 OSS 与 ECS、然后使用内网域名进行上传。
