### ISSUE TITLE
抱歉，您不能访问此页面。

### ISSUE THREAD

**Issue by zhujitop** [juzhiyuan/wordpress-cdn#5]
保存的时候，出现了这个错误：
抱歉，您不能访问此页面。

**Comment by juzhiyuan** [comment]
嗨，在5天前发布了正式版本，修改了插件名称为 `wordpress-cdn`。如果您是在此之前安装的插件，并在安装后更新了该插件（`git pull`），那么就会出现这个问题，这是由于插件目录名称更换导致的。

解决办法：卸载该插件（后台 或者 手动移除 `wp-content/plugins/wordpress-oss` 目录），然后下载正式版本并安装，即可恢复。注意，这需要您在安装后重新做一下配置。之后的版本升级我将注意这个问题，给您的不便表示歉意。

![image](https://user-images.githubusercontent.com/2106987/63225968-49ca4e00-c209-11e9-99f0-40f548b386d6.png)

**Comment by zhujitop** [comment]
会把服务器本地的图片给删掉？

**Comment by juzhiyuan** [comment]
README 中已提示，新上传的图片将不在服务器中保留。

**Comment by juzhiyuan** [comment]
插件的目的就是为了只将数据存在云端，而不占用本地服务器。

**Comment by juzhiyuan** [comment]
暂时关闭该 Issue
