### ISSUE TITLE
点保存的时候出错

### ISSUE THREAD

**Issue by ghost** [juzhiyuan/wordpress-cdn#6]
点保存以后弹出错误:
你不能访问这个页面

**Comment by juzhiyuan** [comment]
这可能是由于不向下兼容的更新造成的，请参考 

https://github.com/juzhiyuan/wordpress-cdn/issues/5#issuecomment-522327864

如果方便可以直接微信联系我 JuShaoyao

**Comment by juzhiyuan** [comment]
经检查，在仓库首页直接下载并解压缩后，插件文件夹名称为 `wordpress-cdn-xxx`，请修改为 `wordpress-cdn`
