### ISSUE TITLE
还是建议可以让用户选择保留本地数据

### ISSUE THREAD

**Issue by zhujitop** [juzhiyuan/wordpress-cdn#7]
如果本地不保存，1太依赖阿里或者腾讯，2就是可能第二天醒来发现账单几千块了...

当然还有支持css、js这些也是基础。

做个功能让用户自己选择是否保留就行了。

还有能走内网吗？

**Comment by juzhiyuan** [comment]
如果需要缓存 CSS、JS 这些静态资源，可以使用已经成熟的 WordPress 插件 :)

目前该插件主要为了 1. 将附件上云、并依赖 CDN 进行加速；2. 减小服务器存储。
