### ISSUE TITLE
Support Lsky Pro

### ISSUE THREAD

**Issue by syhily** [juzhiyuan/wordpress-cdn#8]
Lsky Pro would be a good images manage platform, which internally support the cdn. Adding it could be quite easy.

**Comment by juzhiyuan** [comment]
That's a good idea :) Welcome PR.

**Comment by syhily** [comment]
I'm brand new to php, this would take a long time.

**Comment by juzhiyuan** [comment]
It's ok to have the waiting time :)

**Comment by juzhiyuan** [comment]
I will help you to work with the PR.
