### ISSUE TITLE
无法读取到上传的文件

### ISSUE THREAD

**Issue by venk007** [juzhiyuan/wordpress-cdn#9]
版本：WordPress 5.1.4
安装并配置好插件后，整个网页的媒体文件仍读取服务器本地的。
我在媒体管理中上传了一个图片后，OSS中可以看到对应的多个分辨率图片文件，但是点击查看这个图片，报错404，并没有去读取OSS中的图片，访问的路径是/wp-content/uploads/2019/12/xxx.jpg。
<img width="1680" alt="SCR2019-12-26" src="https://user-images.githubusercontent.com/10581047/71476451-24d19180-2820-11ea-8f40-f1a96bd2ce82.png">

**Comment by juzhiyuan** [comment]
嗨，你可以访问到 https://XXXX/wp-admin/options-general.php?page=wordpress-cdn-plugin 这个地址吗？

![image](https://user-images.githubusercontent.com/2106987/71477718-75e48400-2826-11ea-9bd4-dd81cb2473da.png)

**Comment by juzhiyuan** [comment]
如果希望更快速的解决，我们可以微信聊 :)  微信：jushaoyao

**Comment by juzhiyuan** [comment]
根据微信内聊天记录，该问题产生原因在于未填写 CDN URL。

其实此处不仅仅可以填写 CDN URL，也可以填写 OSS 的外网 URL，但推荐填写前者。

**Comment by juzhiyuan** [comment]
如果填写 CDN URL 后该问题得以解决，请关闭该 Issue :)

**Comment by juzhiyuan** [comment]
如果有其它问题，可以重新创建 Issue 或者重新打开该 Issue。
